replicaCount: 1
nameOverride: ""
fullnameOverride: ""

image:
  repository: ruanbekker/web-center-name-v2
  pullPolicy: IfNotPresent
  tag: "latest"

env:
  vars:
    APP_TITLE: "Welcome"

serviceAccount:
  create: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
