apiVersion: argoproj.io/v1apha1
kind: Application
metadata:
  name: galaxy
  namespace: apps
  finalizers:
    - resources-finalizer.agocd.argoproj.io
spec:
  project: default
  source:
    path: argocd-apps/helm
    repoURL: https://github.com/ruanbekker/argocd-workshop.git
    targetRevision: HEAD
  destination:
    namespace: engineering
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
