apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-center
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: microservice
    repoURL: https://github.com/ruanbekker/helm-charts.git
    targetRevision: HEAD
    helm:
      values: |
        images:
          tag: latest
        env:
          vars:
            APP_TITLE: "Development"
      version: v3
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
